// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlVcw2f1gtkgSQb75OBi_uaqfVvn5u01s',
    appId: '1:23130474318:web:86f0c91f3d91f00065001f',
    messagingSenderId: '23130474318',
    projectId: 'vtuber-335811',
    authDomain: 'vtuber-335811.firebaseapp.com',
    databaseURL: 'https://vtuber-335811-default-rtdb.firebaseio.com',
    storageBucket: 'vtuber-335811.appspot.com',
    measurementId: 'G-8V8T0DDBMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgD_rVs0XqlmQnEAtFWd45ZDoRWDFsqjE',
    appId: '1:23130474318:android:bf5b2d9f79a5a80f65001f',
    messagingSenderId: '23130474318',
    projectId: 'vtuber-335811',
    databaseURL: 'https://vtuber-335811-default-rtdb.firebaseio.com',
    storageBucket: 'vtuber-335811.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAZcP9e7a279Q0pNWNKGE3hLCfsOvL-xM',
    appId: '1:23130474318:ios:c6c19a1565e52e8f65001f',
    messagingSenderId: '23130474318',
    projectId: 'vtuber-335811',
    databaseURL: 'https://vtuber-335811-default-rtdb.firebaseio.com',
    storageBucket: 'vtuber-335811.appspot.com',
    iosClientId: '23130474318-3ipaso03mf2jau7lhi73rnr823uqufr2.apps.googleusercontent.com',
    iosBundleId: 'vtuberchannel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAZcP9e7a279Q0pNWNKGE3hLCfsOvL-xM',
    appId: '1:23130474318:ios:899867422132c2b865001f',
    messagingSenderId: '23130474318',
    projectId: 'vtuber-335811',
    databaseURL: 'https://vtuber-335811-default-rtdb.firebaseio.com',
    storageBucket: 'vtuber-335811.appspot.com',
    iosBundleId: 'vtuberchannel.vtuberchannel.RunnerTests',
  );
}
